<html>
    <head>
        <meta charset="utf-8"/>
        <title>Slim 3</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <style>
            body {
                margin: 50px;
                padding: 0;
                width: 90%;
                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
                text-align: center;
                color: #aaa;
                font-size: 18px;
            }

            h1 {
                color: #719e40;
                letter-spacing: -3px;
                font-family: 'Lato', sans-serif;
                font-size: 100px;
                font-weight: 200;
                margin-bottom: 0;
            }
        </style>

        <script src="https://hub.loginradius.com/include/js/LoginRadius.js"></script>
        <script type="text/javascript"> var options={}; options.login=true; LoginRadius_SocialLogin.util.ready(function () { $ui = LoginRadius_SocialLogin.lr_login_settings;$ui.interfacesize = "";$ui.apikey = "68586157-f6b4-493f-9a7c-bebfe80d82a3";$ui.callback="http://localhost/login-callback"; $ui.lrinterfacecontainer ="interfacecontainerdiv"; LoginRadius_SocialLogin.init(options); }); </script>




    </head>
    <body>
        <h1>Login Radius Demo</h1>
        <div>Please Login Using Facebook App</div>

        <hr>
        <div id="interfacecontainerdiv" class="interfacecontainerdiv"></div>

        <div>
            <br>
             <br>

        </div>
    </body>
</html>
