<html>
    <head>
        <meta charset="utf-8"/>
        <title>Slim 3</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <style>
            body {
                margin: 50px 0 0 0;
                padding: 0;
                width: 100%;
                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
                text-align: center;
                color: #aaa;
                font-size: 18px;
            }

            h1 {
                color: #719e40;
                letter-spacing: -3px;
                font-family: 'Lato', sans-serif;
                font-size: 100px;
                font-weight: 200;
                margin-bottom: 0;
            }
        </style>
    </head>
    <body>
        <h1>Login Radius Demo</h1>
        <div>Please Login or Register</div>

        <div class="col-md-12 col-sm-6">
            <div style="align-content: center; border: 2px solid #3b5998; ">
                <form action="/login" method="post">
                    <input type="email" name="email" required placeholder="Your email please">
                    <input type="password" name="password" required placeholder="Your password please">
                    <input type="submit" name="submit" value="Login">
                    <input type="reset" name="reset" value="Reset">
                </form>
            </div>

        </div>
    </body>
</html>
